### [GET] Lista todos os usuários
GET http://localhost:8080/users
Content-Type: application/json

###

### [POST] Cria um novo usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Lucas",
  "email": "lucas@email.com"
}

###

### [GET] Busca um usuário por ID
GET http://localhost:8080/users/1
Content-Type: application/json

###

### [PUT] Atualiza o usuário com ID 1
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Lucas Silva",
  "email": "lucas.silva@email.com"
}

###

### [DELETE] Deleta o usuário com ID 1
DELETE http://localhost:8080/users/1
Content-Type: application/json
